server:
  port: 8081

logging:
  level:
    org.flywaydb: INFO
    org.springframework.boot.autoconfigure.flyway: DEBUG

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://core-db:5432/quickstock_core


payments:
  base-url: http://payments-service:8082
