server:
  port: 8082

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
    org.springframework.boot.flyway.autoconfigure: DEBUG

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://payments-db:5432/quickstock_payments
  flyway:
    enabled: true
    url: jdbc:postgresql://payments-db:5432/quickstock_payments
    user: quickstock
    password: secret
    locations: classpath:db/migration

core:
  base-url: http://quickstock-core-service:8081
