server:
  port: 8082

logging:
  level:
    org.flywaydb: INFO
    org.springframework.boot.autoconfigure.flyway: DEBUG

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://payments-db:5432/quickstock_payments

core:
  base-url: http://quickstock-core-service:8081
