server:
  port: 8082

logging:
  level:
    org.flywaydb: INFO
    org.springframework.boot.autoconfigure.flyway: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://payments-db:5432/quickstock_payments
    username: quickstock
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

core:
  base-url: http://quickstock-core-service:8081
